COLUNAS_PRINCIPAIS = [
    "COD FILIAL",
    "FILIAL",
    "BASE",
    "SIGLA",
    "ESTADO",
    "SENHA",
    "COMPLICACAO",
    "OBITO",
    "COD USUARIO",
    "USUARIO",
    "TELEFONE",
    "IDADE",
    "IDADE T",
    "EMPRESA",
    "COD PLANO",
    "PLANO",
    "DT ADESAO",
    "TEMPO PLANO",
    "DIAS CARENCIA",
    "TP ATENDIMENTO",
    "TRATAMENTO",
    "PRESTADOR",
    "SOLICITANTE",
    "COD PROCEDIMENTO",
    "PROCEDIMENTO",
    "DT AUTORIZACAO",
    "DT INTERNACAO",
    "DT ENVIO",
    "DIARIAS",
    "UTI",
    "OBSERVACAO",
    "CHAVE",
    "OPERADOR",
    "CONTATO",
    "DT ENVIO MANUAL",
    "DATA DO CONTATO",
    "LIDA",
    "RESPOSTA",
    "STATUS",
    "DATA DE ENVIO",
    "P1",
    "P2",
    "P3",
    "P4",
    "OBSERVAÇÕES DO CLIENTE",
    "RP1",
    "RP1 NÂº",
    "TENTATIVA",
    "DATA ULTIMA TENTATIVA",
    "TELEFONE TENTADO",
    "ESPECIALISTA",
    "TIPO",
    "UF",
    "DISTRITO",
    "TELEFONE 1",
    "TELEFONE 2",
    "TELEFONE 3",
    "TELEFONE 4",
    "TELEFONE 5",
]

COLUNAS_PESQUISA = [
    "Data",
    "Nome",
    "Telefone",
    "CPF/CNPJ",
    "Resposta",
    "Opção",
    "Protocolo",
    "Cod.",
    "Número externo",
    "Agente",
    "Canal",
    "Conta",
    "Serviço",
    "UF",
    "Classificação",
    "Entrada",
    "Classificação de IA",
]

ABAS_AJUSTADAS = {
    "STATUS": [
        "Conta",
        "HSM",
        "Mensagem",
        "Categoria",
        "Template",
        "Data do envio",
        "Status",
        "Respondido",
        "protocolo",
        "Agendamento",
        "Data agendamento",
        "Status agendamento",
        "Campanha",
        "Agente",
        "Contato",
        "Telefone",
        "ID_Mailing",
        "DT ENVIO",
        "RESPOSTA",
        "NOME_MANIPULADO",
    ],
    "P1": COLUNAS_PESQUISA,
    "P2": COLUNAS_PESQUISA,
    "P3": COLUNAS_PESQUISA,
    "P4": COLUNAS_PESQUISA,
    "CHAVE ERRO": [
        "CHAVE ERRADA",
        "P1",
        "P2",
        "P3",
        "P4",
        "CHAVE CERTA",
    ],
    "RESUMO": [],
}

PALAVRAS_PRIORITARIAS = [
    # Prioridades originais
    "CESARIANA",
    "PARTO",
    # Primeiras palavras da coluna PROC_1 (fixas no codigo)
    "ABLACAO",
    "AMIGDALECTOMIA",
    "AMPUTACAO",
    "ANEURISMA",
    "ANGIOPLASTIA",
    "ANOMALIA",
    "APENDICECTOMIA",
    "ARTRITE",
    "ARTRODESE",
    "ARTROPLASTIA",
    "ARTROTOMIA",
    "BRONCOSCOPIA",
    "COLECISTECTOMIA",
    "COLECTOMIA",
    "COLPOPLASTIA",
    "DILATACAO",
    "ENXERTO",
    "EPISTAXE",
    "FACECTOMIA",
    "FISTULECTOMIA",
    "GASTROPLASTIA",
    "HERNIA",
    "HERNIORRAFIA",
    "HISTERECTOMIA",
    "HISTEROSCOPIA",
    "LAPAROTOMIA",
    "LIPOASPIRACAO",
    "MAMOPLASTIA",
    "ORQUIDOPEXIA",
    "OSTEOPLASTIAS",
    "PTERIGIO",
    "QUADRANTECTOMIA",
    "QUIMIOEMBOLIZACAO",
    "RECONSTRUCAO",
    "RUPTURA",
    "SEPTOPLASTIA",
    "TROCA",
    "URETERORRENOLITOTRIPSIA",
]
